version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:latest

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp/gcp-key.json
    volumes:
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/dags:/opt/airflow/dags
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/gcp:/opt/airflow/gcp
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/dbt:/opt/airflow/dbt
      - ./dags:/opt/airflow/dags
      - ./gcp:/opt/airflow/gcp
      - ./dbt:/opt/airflow/dbt
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp/gcp-key.json
    volumes:
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/dags:/opt/airflow/dags
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/gcp:/opt/airflow/gcp
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/dbt:/opt/airflow/dbt
      - ./dags:/opt/airflow/dags
      - ./gcp:/opt/airflow/gcp
      - ./dbt:/opt/airflow/dbt
    command: airflow scheduler

  airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp/gcp-key.json
    volumes:
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/dags:/opt/airflow/dags
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/gcp:/opt/airflow/gcp
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/dbt:/opt/airflow/dbt
      - ./dags:/opt/airflow/dags
      - ./gcp:/opt/airflow/gcp
      - ./dbt:/opt/airflow/dbt
    command: airflow celery worker

  airflow-init:
    image: apache/airflow:2.7.2-python3.10
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    volumes:
      # - /mnt/d/Rajat_Projects/GCP_Airflow_Looker_project/dags:/opt/airflow/dags
      - ./dags:/opt/airflow/dags
    command: airflow db migrate

volumes:
  postgres_db:
